### ISSUE TITLE
common.type not set for devices (warning)

### ISSUE THREAD

**Issue by guerda** [mobilutz/ioBroker.freeathome#432]
**Describe the bug**  
I reinstalled ioBroker and installed ioBroker.freeAtHome. Currently, a lot of devices are reported with the following error message:

    Object of state "freeathome.1.ABBxxxxxxx.deviceId" is missing the required property "common.type"

This is just an example, it returns for > 100 log entries. 
**To Reproduce**  
1. Install adapter
2. Configure instance 
3. Look at log for this adapter.

**Expected behavior**  
No warnings :)

**Versions:**  
 - Adapter version: v0.0.10
 - JS-Controller version: v4.0.21
 - Node version: v14.19.0
 - Operating system: Raspbian 11

**Comment by guerda** [comment]
For me it looks like we need to add it here, depending on the device type:
https://github.com/mobilutz/ioBroker.freeathome/blob/516b928ec434c490f062c2df0349d656e0db39e4/lib/freeathome.js#L70

**Comment by guerda** [comment]
The freeathome-api provides information like `functionId` which might help us in this case to categorize the type.

**Comment by guerda** [comment]
In my opinion, the `functionId` the API provides for both devices and channels can be used to determine the `common.type`.
[Full list of functionIds](https://developer.eu.mybuildings.abb.com/fah_cloud/reference/functionids/)

e.g. 
* 0x0000 | FID_SWITCH_SENSOR must be boolean
* 0x0012 | FID_DIMMING_ACTUATOR must be a number

[Full list of types](https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/adapterpublish.md)


@mobilutz What do you think of this approach to map functionIds to common.types?

**Comment by mobilutz** [comment]
@guerda This sure sounds like a very good idea! 

I will try to get to this as soon as possible.

**Comment by guerda** [comment]
Work in progress in #480

**Comment by esusxunil** [comment]
I had the same issue and it is not mandatory to set the common.type based on the function.

The problem is that the functionId for the entire channel, but the type needs to be set to every single datapoint. A Channel with functionId 0x0000 can still have a name ("string") or a status ("boolean") or any other type as well.

If - then the type needs to be set based on the pairingID, which is available in the API but not exposed by the adapter.

https://developer.eu.mybuildings.abb.com/fah_cloud/reference/pairingids/

The good thing is - when I look into Swagger API, then all values delivered back are always from type string. 

I solved this for me with a small skript:

`    var INSTANCE = "freeathome.0"
    var ALL = INSTANCE + ".*.*.*";
    var DEVICEIDS = INSTANCE + ".*.deviceId";
    
    $(ALL).each(async function (id) { 
        var tempObject = getObject(id);
        if (typeof(tempObject.common.type) == 'undefined') {
            tempObject.common.type = "string";
            await setObjectAsync(id, tempObject);
            log("Updated common.type to string for Channel " + id, "info");
        }
    });

    $(DEVICEIDS).each(async function (id) { 
        var tempObject = getObject(id);
        if (typeof(tempObject.common.type) == 'undefined') {
            tempObject.common.type = "string";
            await setObjectAsync(id, tempObject);
            log("Updated common.type to string for Channel " + id, "info");
        }
    });`

**Comment by mobilutz** [comment]
This was added in https://github.com/mobilutz/ioBroker.freeathome/commit/68177ae9efbb1051f959997e7887c0f2977e31f0
